export const MAP_SETCENTER = 'MAP::SET_CENTER'
export const MODAL_LOGIN = 'LAYOUT::OPEN_LOGIN'
export const SET_LEFT_PANEL = 'LAYOUT::SET_LEFT_PANEL'
export const MODAL_PROFILE = 'LAYOUT::OPEN_PROFILE'
